# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Life Lofranco
email: lifelofranco@lifelofranco.com
description: Enthusiast. Traveler. Developer.
baseurl: "lifelofranco/" # the subpath of your site, e.g. /blog
url: "http://lifelofranco.com" # the base hostname & protocol for your site
twitter_username: LifeLofranco
github_username:  lifelofranco
excerpt_separator: "<!--excerpt-->"
# Build settings
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false

# Google services
google_analytics: UA-86630300-2
facebook_app_id: 1586840631617904
